VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "freeSwitch"
  config.vm.box = "debian/stretch64"
  config.vm.synced_folder ".", "/vagrant",
    :mount_options => ["dmode=777,fmode=777"]
  
	config.vm.provision "ansible" do |ansible|
		ansible.playbook = "freeswitch_base.yml"
	end

  config.vm.provider :virtualbox do |vb|
    vb.memory = 1024
    config.vm.network "private_network", type: "dhcp", :adapter => 2    
  end

end
