VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "asterisk"
  config.vm.box = "debian/testing64"
  config.vm.synced_folder ".", "/vagrant",
    :mount_options => ["dmode=777,fmode=777"]

  config.vm.provision "", type: "ansible" do |ansible|
    ansible.playbook = "build/38008_server.yml"
  end

  # forwards default to TCP
  config.vm.provider :virtualbox do |vb|
    vb.memory = 1024
    config.vm.network "private_network", type: "dhcp", :adapter => 2    
    config.vm.network "forwarded_port", guest: 2000, host: 2000
    # SCCP voice ports
    for p in 16384..19384
      config.vm.network "forwarded_port", guest: p, host: p
    end
  end

end
